include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true
    cancel_subscriptions: true
    close_sinks: true
    use_super_parameters: true
